version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: openregister
      POSTGRES_USER: openregister-info
      POSTGRES_DB: openregister-info_development
      PGDATA: /var/lib/postgresql/data/pgdata
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SELF_SERVICE_HTTP_AUTH_USERNAME: ${SELF_SERVICE_HTTP_AUTH_USERNAME}
      SELF_SERVICE_HTTP_AUTH_PASSWORD: ${SELF_SERVICE_HTTP_AUTH_PASSWORD}

volumes:
  data: {}
